---
- name: Remove unstable ONL APT repo
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/multistrap-onl.list
    state: absent

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: no

- name: Set dependencies
  set_fact:
    dependencies:
      system: "{{ lookup('vars', (ansible_distribution | lower)+ '_'+ (ansible_distribution_major_version) +'_dependencies')}}"
      python: "{{ python_packages }}"
