---
# tasks file for docker
- name: Install ca-certificates and curl
  apt:
    name: "ca-certificates, curl"
    state: latest
    update_cache: true

- name: Create directory /etc/apt/keyrings
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: yes

- name: Download Docker key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
  become: yes

- name: Grant read permissions to Docker.asc file
  file:
    path: /etc/apt/keyrings/docker.asc
    mode: 'a+r'
  become: yes

- name: Add Docker repository to Apt sources
  shell: >
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  become: yes

- name: Update package information
  apt:
    update_cache: yes
  become: yes

- name: Install Docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes
  become: yes

- name: Start Docker service
  systemd:
    name: docker
    state: started
    enabled: yes
  become: yes



