apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: p4-macvlan-${IFNAME}
spec:
  config: '{
            "cniVersion": "0.3.0",
            "type": "macvlan",
            "master": ${NODE_NETIF},
            "mode": "bridge",
            "ipam": {
                "type": "host-local",
                "ranges": [
                    [ {
                         "subnet": "192.168.100.0/24",
                         "rangeStart": "192.168.100.162",
                         "rangeEnd": "192.168.100.192"
                    } ]
                ]
            }
        }'
