---
- include_tasks: "{{ 'docker_' + (ansible_distribution | lower) + '.yaml' }}"

# install Go
- name: Download Go
  ansible.builtin.get_url:
    url: https://storage.googleapis.com/golang/getgo/installer_linux
    dest: './installer_linux'
    mode: '0500'
- name: Install Go
  ansible.builtin.shell: './installer_linux'

# install cri-dockerd
- name: Retrieve cri-dockerd (1/2)
  ansible.builtin.git:
    repo: https://github.com/Mirantis/cri-dockerd.git
    dest: cri-dockerd
    version: v0.3.1
    force: yes
- name: Retrieve cri-dockerd (2/2)
  ansible.builtin.file:
    path: ./cri-dockerd/bin
    state: directory

- name: Build cri-dockerd
  ansible.builtin.shell: '/root/.go/bin/go build -o bin/cri-dockerd'
  args:
    chdir: ./cri-dockerd
  environment:
    GOPATH: /root/.go

- name: Install cri-dockerd (1/4)
  ansible.builtin.file:
    path: /usr/local/bin
    state: directory

- name: Install cri-dockerd (2/4)
  ansible.builtin.shell: 'install -o root -g root -m 0755 bin/cri-dockerd /usr/local/bin/cri-dockerd'
  args:
    chdir: ./cri-dockerd

- name: Install cri-dockerd (3/4)
  ansible.builtin.shell: 'cp -a packaging/systemd/* /etc/systemd/system'
  args:
   chdir: ./cri-dockerd

- name: Install cri-dockerd (4/4)
  ansible.builtin.shell: "sed -i -e 's,/usr/bin/cri-dockerd,/usr/local/bin/cri-dockerd,' /etc/systemd/system/cri-docker.service"
  args:
    chdir: ./cri-dockerd

- name: Enable and start cri-docker service
  ansible.builtin.systemd:
    name: cri-docker.service
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Enable and start cri-docker socket
  ansible.builtin.systemd:
    name: cri-docker.socket
    state: restarted
    enabled: yes
    daemon_reload: yes