{
 "title": "OAI Logs Dashboard",
 "description": "Loki dashboard with quick search and timeline.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "workload",
    "query": "label_values(mixin_pod_workload{namespace=\"$namespace\"}, workload)"
   },
   {
    "name": "pod",
    "query": "label_values(mixin_pod_workload{namespace=\"$namespace\", workload=\"$workload\"}, pod)"
   },
   { "name": "search" }
  ]
 },
 "panels": [
  {
   "title": "Timeline",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", app=\"$workload\", instance=~\"$pod\"} |~ \"$search\"[$__interval]))"
    }
   ]
  },
  {
   "title": "UPF Logs",
   "type": "logs",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "{app_kubernetes_io_name=\"oai-upf\",namespace=\"blueprint\"}"
    }
   ]
  },
  {
   "title": "AMF Logs",
   "type": "logs",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "{app_kubernetes_io_name=\"oai-amf\",namespace=\"blueprint\"}"
    }
   ]
  },
  {
   "title": "SMF Logs",
   "type": "logs",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "{app_kubernetes_io_name=\"oai-smf\",namespace=\"blueprint\"}"
    }
   ]
  },
  {
   "title": "UDR Logs",
   "type": "logs",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "{app_kubernetes_io_name=\"oai-udr\",namespace=\"blueprint\"}"
    }
   ]
  },
  {
   "title": "AUSF Logs",
   "type": "logs",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "{app_kubernetes_io_name=\"oai-ausf\",namespace=\"blueprint\"}"
    }
   ]
  },
  {
   "title": "NRF Logs",
   "type": "logs",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "{app_kubernetes_io_name=\"oai-nrf\",namespace=\"blueprint\"}"
    }
   ]
  },
  {
   "title": "UDM Logs",
   "type": "logs",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "{app_kubernetes_io_name=\"oai-udm\",namespace=\"blueprint\"}"
    }
   ]
  },
  {
   "title": "MySQL Logs",
   "type": "logs",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "{app_kubernetes_io_name=\"basic-mysql\",namespace=\"blueprint\"}"
    }
   ]
  }
 ]
}