---
- name: Initialize k8s cluster
  hosts: masters[0]
  become: yes
  environment:
    PATH: '{{ansible_env.PATH }}:/usr/local/bin/'

  roles:
    - role: k8s-master
    - role: k8s-ca-certificate
    - role: k8s-infos

  post_tasks:
    - name: Wait for the node to be ready
      ansible.builtin.include_tasks: k8s-ready.yaml

- name: Attach masters
  hosts: masters[1:]
  become: yes
  vars:
    token: "{{ hostvars['ansible_dummy_host']['_token'] }}"
    ca_cert_hash: "{{ hostvars['ansible_dummy_host']['_ca_cert_hash'] }}"
    certificate_key: "{{ hostvars['ansible_dummy_host']['_certificate_key'] }}"
    kube_config_local_path: "{{ hostvars['ansible_dummy_host']['_kube_config'] }}"
    master: "{{ k8s['apiserver_advertise_address'] | default(hostvars['ansible_dummy_host']['_master']) }}"
    control_plane_node: true
  environment:
    PATH: '{{ansible_env.PATH }}:/usr/local/bin/'

  roles:
    - role: k8s-node
    - role: k8s-ca-certificate

  post_tasks:
    - name: Wait for the node to be ready
      ansible.builtin.include_tasks: k8s-ready.yaml

- name: Install cluster monitoring
  hosts: masters[0]
  vars:
    remote_write_address: "{{ k8s['cluster_monitoring']['prometheus']['remote_write_address'] }}"
    remote_write_port: "{{ k8s['cluster_monitoring']['prometheus']['remote_write_port'] }}"
    remote_write_user: "{{ k8s['cluster_monitoring']['prometheus']['remote_write_user'] }}"
    remote_write_pass: "{{ k8s['cluster_monitoring']['prometheus']['remote_write_pass'] }}"
    remote_data_label: "{{ k8s['cluster_monitoring']['prometheus']['remote_data_label'] }}"
    loki_address: "{{ k8s['cluster_monitoring']['promtail']['loki_address'] }}"
    loki_port: "{{ k8s['cluster_monitoring']['promtail']['loki_port'] }}"
    loki_label: "{{ k8s['cluster_monitoring']['promtail']['loki_label'] }}"

  roles:
    - post-5g-bp-cluster-monitoring/prometheus
    - post-5g-bp-cluster-monitoring/promtail
    - post-5g-bp-cluster-monitoring/cadvisor
    - post-5g-bp-cluster-monitoring/node-exporter
    - post-5g-bp-cluster-monitoring/kube-state-metrics
  
