---
# 5G config
GCN:
  namespace: blueprint
  RAN:
    present: true
    custom_files: blueprint/ran/files
    custom_values: blueprint/ran/values
    split:
      e1: false
      f1: false
  UE:
    present: true
    tests:
      landmark_ping:
          landmark: 172.22.10.1
