---
# k8s config
k8s:
  runtime: docker
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/16
  dnsDomain: cluster.local
  apiserver_advertise_address: 172.16.12.151
  calico:
    nodeAddressAutodetectionV4:
      cidrs:
        #- 10.0.1.0/24
        - 172.16.12.0/24
  encapsulation: VXLAN
  cluster_monitoring:
    prometheus:
      remote_write_address: "10.64.45.228"
      remote_write_port: "9090"
      remote_write_user: "admin"
      remote_write_pass: "test1234"
      remote_data_label: "uth-cluster1"
    promtail:
      loki_address: 10.64.45.228
      loki_port: 3100
central_monitor:
  prometheus:
    prometheus_basic_auth_user: 'admin'
    prometheus_basic_auth_password: 'test1234'

